# Generated by Django 4.1.1 on 2023-04-06 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
