# Generated by Django 4.1.1 on 2023-04-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_products',
            field=models.IntegerField(default=0),
        ),
    ]
