# Generated by Django 4.1.1 on 2023-04-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addr2',
            new_name='addr1',
        ),
    ]
