# Generated by Django 4.1.1 on 2023-04-07 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
