# Generated by Django 4.1.1 on 2023-04-07 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_address_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='cart_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
