# Generated by Django 4.1.1 on 2023-04-07 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_addtocart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_cartdata', to='core.product'),
        ),
    ]
