# Generated by Django 4.1.1 on 2023-04-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_addtocart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_customer', to='core.customer'),
        ),
    ]
