# Generated by Django 4.1.1 on 2023-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_addtocart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='num_of_products',
            field=models.IntegerField(default=0),
        ),
    ]
