# Generated by Django 4.1.1 on 2023-04-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_addtocart_num_of_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
